# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: Release

on:
 push:
  tags:
    - 'v*'
    
jobs:
  ReleaseApp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'
      - name: Run Maven package
        run: mvn package
      - name: List files
        run: ls -la target/
      - name: Create release
        uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: "target/my-ecommerce-0.1.jar"
          body: "Release of version ${{ github.ref }}"
          name: "Release ${{ github.ref }}"
