# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: Run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  RunUnitTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'
          cache: 'maven'
      - name: Run the Maven verify phase
        run: mvn test
      
